name: Karate DSL Regression Tests

on:
  push:
    branches:
      - staging

jobs:
  karate_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Run Karate Tests
        run: mvn test "-Dkarate.options=--tags ${{ github.event.inputs.test_tags }}"

    env:
      TEST_TAGS: ${{ github.event.inputs.test_tags }}
